pipeline {
  agent any
  
  stages {
    stage('Git fetch') {
      steps {
        echo 'Git fetch'
        git url: 'https://github.com/KHS-SK/spring-petclinic/',
          branch: 'main', credentialsId: 'gitCredential'
      }
    }
    stage('Maven Hello') {
      steps {
        echo 'Maven Build'
      }
    }
    stage('Docker Image') {
      steps {
        echo 'Docker Image'
      }
    }
    stage('Image Push') {
      steps {
        echo 'Image Push'
      }
    }
    stage('Codedeploy Workload') {
      steps {
        echo 'Codedeploy Workload'
      }
    }
  }
}
